// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGSau9mIAV7KajedApvpmNP4lAqSUy37w',
    appId: '1:949866131501:web:262211f3279bc27a3008a4',
    messagingSenderId: '949866131501',
    projectId: 'delcare-ai',
    authDomain: 'delcare-ai.firebaseapp.com',
    storageBucket: 'delcare-ai.firebasestorage.app',
    measurementId: 'G-B1KNKSVFR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFcLYqReHIfXMF0Y2GhUB6VNpD31-Ob1A',
    appId: '1:949866131501:android:70579ff50259d5223008a4',
    messagingSenderId: '949866131501',
    projectId: 'delcare-ai',
    storageBucket: 'delcare-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7WGdPPAKNwEcs2-RK_zbWZO6Rru1haEA',
    appId: '1:949866131501:ios:71f263aece770c063008a4',
    messagingSenderId: '949866131501',
    projectId: 'delcare-ai',
    storageBucket: 'delcare-ai.firebasestorage.app',
    iosBundleId: 'com.example.emolensApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7WGdPPAKNwEcs2-RK_zbWZO6Rru1haEA',
    appId: '1:949866131501:ios:71f263aece770c063008a4',
    messagingSenderId: '949866131501',
    projectId: 'delcare-ai',
    storageBucket: 'delcare-ai.firebasestorage.app',
    iosBundleId: 'com.example.emolensApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGSau9mIAV7KajedApvpmNP4lAqSUy37w',
    appId: '1:949866131501:web:a16a2fa4b941d60c3008a4',
    messagingSenderId: '949866131501',
    projectId: 'delcare-ai',
    authDomain: 'delcare-ai.firebaseapp.com',
    storageBucket: 'delcare-ai.firebasestorage.app',
    measurementId: 'G-59ZMDZCXVL',
  );
}
